blog/urls.py
from django.urls import path
from blog.views import BlogCard
from django.views.decorators.cache import cache_page


app_name = "blog"

urlpatterns = [
    path("blog_card/<slug:blog_slug>", cache_page(60)(BlogCard.as_view()), name="blog_card"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from mailing.views import MessagesView, ClientsView, MainView, MessageCreate, TransmissionCreate, \
    TransmissionView, TransmissionDelete, MessageDelete, TransmissionCard, TransmissionUpdate, \
    MessageCard, MessageUpdate, ClientDelete, ClientCard, ClientCreate, ClientUpdate


app_name = "mailing"

urlpatterns = [
    path("", MainView.as_view(), name="main_page"),
    path("messages/", MessagesView.as_view(), name="messages"),
    path("message_create/", MessageCreate.as_view(), name="message_create"),
    path("message_delete/<slug:message_slug>", MessageDelete.as_view(), name="message_delete"),
    path("message_update/<slug:message_slug>", MessageUpdate.as_view(), name="message_update"),
    path("message_card/<slug:message_slug>", MessageCard.as_view(), name="message_card"),
    path("clients/", ClientsView.as_view(), name="clients"),
    path("client_create/", ClientCreate.as_view(), name="client_create"),
    path("client_delete/<slug:client_slug>", ClientDelete.as_view(), name="client_delete"),
    path("client_update/<slug:client_slug>", ClientUpdate.as_view(), name="client_update"),
    path("client_card/<slug:client_slug>", ClientCard.as_view(), name="client_card"),
    path("transmissions/", TransmissionView.as_view(), name="transmissions"),
    path("transmission_create/", TransmissionCreate.as_view(), name="transmission_create"),
    path("transmission_delete/<slug:transmission_slug>", TransmissionDelete.as_view(), name="transmission_delete"),
    path("transmission_update/<slug:transmission_slug>", TransmissionUpdate.as_view(), name="transmission_update"),
    path("transmission_card/<slug:transmission_slug>", TransmissionCard.as_view(), name="transmission_card"),
]

mailing/models.py
from config import settings
import django as django
from django.db import models
from mailing.services import convert_word


class Clients(models.Model):
    """Model of client for sending"""
    full_name = models.CharField(max_length=100, verbose_name="client name", null=False, blank=False, unique=True)
    comment = models.TextField(max_length=500, null=True, blank=True, verbose_name="comment about client")
    email = models.EmailField(max_length=255,  verbose_name="client mail", null=False, blank=False, unique=False)
    slug = models.SlugField(max_length=255, verbose_name="client slug", null=False, unique=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name = "Client"
        verbose_name_plural = "Clients"

    def __str__(self):
        """Return client mail for fast sending"""
        return self.email

    def save(self, *args, **kwargs):
        """Save slug to clients base"""
        if not self.slug:
            self.slug = convert_word(self.full_name)
        super().save(*args, **kwargs)


class Transmission(models.Model):
    """Model transmission for sending"""

    class TransmissionStatus(models.TextChoices):
        Finished = 'FINISHED'
        Created = 'CREATED'
        Running = 'READY'
        Finished_error = 'FINISHED_WITH_ERROR'

    class TransmissionFrequency(models.TextChoices):
        Daily = 'DAILY'
        Weekly = 'WEEKLY'
        Monthly = 'MONTHLY'

    title = models.CharField(max_length=100, verbose_name="transmission name", null=False, blank=False, unique=True)
    time = models.TimeField(verbose_name="start time for sending", default=django.utils.timezone.now)
    frequency = models.CharField(choices=TransmissionFrequency.choices)
    status = models.CharField(choices=TransmissionStatus.choices, default=TransmissionStatus.Created)
    message = models.ForeignKey("Messages", on_delete=models.SET_NULL, null=True, blank=True)
    clients = models.ManyToManyField("Clients")
    slug = models.SlugField(max_length=255, verbose_name="transmission slug", null=False, unique=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    is_published = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Transmission"
        verbose_name_plural = "Transmission Templates"

    def save(self, *args, **kwargs):
        """Save slug to transmission base"""
        if not self.slug:
            self.slug = convert_word(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Transmission: {self.title}"

    def get_statistic(self):
        """Get statistic of send. Use Related name in Statistic"""
        return self.statistic_of_transmission.all()

    def get_messages(self):
        """Get message for transmission when used scheduler"""
        messages = self.message
        return messages

    def get_clients(self):
        """Get clients for transmission when used scheduler"""
        clients = self.clients.all()
        return clients


class Messages(models.Model):
    """Model message for clients for sending"""
    theme = models.CharField(max_length=50, verbose_name="message theme", null=False, blank=False, unique=True)
    body = models.TextField(max_length=500, verbose_name="message body", null=False, blank=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    slug = models.SlugField(max_length=255, verbose_name="message slug", null=False, unique=True)

    class Meta:
        verbose_name = "Message"
        verbose_name_plural = "Messages"

    def __str__(self):
        return self.theme

    def get_info(self):
        """Return information about message for fast sending"""
        return self.theme, self.body

    def save(self, *args, **kwargs):
        """Save slug to message base"""
        if not self.slug:
            self.slug = convert_word(self.theme)
        super().save(*args, **kwargs)


class Statistic(models.Model):
    """Model for statistic of transmissions"""

    class AttemptStatus(models.TextChoices):
        Finished = 'FINISHED'
        Created = 'CREATED'

    transmission = models.ForeignKey("Transmission", on_delete=models.CASCADE, related_name="statistic_of_transmission")
    time = models.DateTimeField(verbose_name="last time for send", default=None, null=True, blank=True)
    status = models.CharField(choices=AttemptStatus.choices, default=AttemptStatus.Created)
    mail_answer = models.CharField(verbose_name="answer from mailserver", default=None, null=True, blank=True)

    class Meta:
        verbose_name = "Statistic"
        verbose_name_plural = "Statistics"

    def __str__(self):
        return f"Status: {self.status} Time: {self.time} Mail answer: {self.mail_answer}"

mailing/views.py
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
import config.settings
from mailing.models import Messages, Clients, Transmission
from mailing.services import sendmail
from mailing.forms import TransmissionCreateForm, Statistic, ClientCreateForm, MessageCreateForm
from blog.models import Blog
from django.core.cache import cache


class MainView(LoginRequiredMixin, ListView):
    """Main page with blog and statistic"""
    model = Messages
    template_name = "mailing/main.html"

    def get_queryset(self):
        """Execute blog part cash on main page"""
        if config.settings.CACHE_ENABLED:
            key = 'main_blog'
            cache_data = cache.get(key)
            if cache_data is None:
                cache_data = Blog.objects.order_by('?')[:3]
                cache.set(key, cache_data)
        else:
            cache_data = Blog.objects.order_by('?')[:3]
        return cache_data

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Main"
        # show blogs
        context["Blog"] = self.get_queryset()
        # show statistic
        context["all_transmissions"] = len(Transmission.objects.all())
        context["active_transmissions"] = len(Transmission.objects.filter(is_published=True))
        context["all_clients"] = len(Clients.objects.all())
        context["unique_clients"] = len(Clients.objects.all().values('email').distinct())
        return context


class ClientsView(ListView):
    """Show all clients for owner / moderator / admin"""
    model = Clients
    template_name = "mailing/clients.html"

    def get_queryset(self):
        queryset = super().get_queryset().all()
        if not self.request.user.is_staff:
            queryset = super().get_queryset().filter(owner=self.request.user)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Clients"
        context["Clients"] = self.get_queryset()
        return context


class ClientCard(DetailView):
    """Show all information about client"""
    model = Clients
    template_name = "mailing/client_card.html"
    slug_url_kwarg = "client_slug"

    def get_object(self, queryset=None):
        one_client = super().get_object()
        return one_client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Client Full Information"
        context["Client"] = self.get_object()
        return context


class ClientCreate(CreateView):
    """Create client"""
    model = Clients
    form_class = ClientCreateForm
    template_name = "mailing/client_create.html"

    def get_context_data(self, *, object_list=None, context_object_name=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Add New Client"
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('mailing:clients')

    def form_valid(self, form):
        # save owner of user
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientUpdate(UpdateView):
    """Update client"""
    model = Clients
    fields = ["full_name", "comment", "email"]
    template_name = "mailing/client_update.html"
    slug_url_kwarg = "client_slug"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Update Client"
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('mailing:clients')

    def form_valid(self, form):
        return super().form_valid(form)


class ClientDelete(DeleteView):
    """Delete client"""
    model = Clients
    template_name = "mailing/delete.html"
    slug_url_kwarg = "client_slug"

    def get_context_data(self, *, object_list=None, context_object_name=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Delete Client"
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('mailing:clients')


class MessagesView(ListView):
    """Show all message for owner / moderator / admin"""
    model = Messages
    template_name = "mailing/messages.html"

    def get_queryset(self):
        queryset = super().get_queryset().all()
        if not self.request.user.is_staff:
            queryset = super().get_queryset().filter(owner=self.request.user)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Messages"
        context["Messages"] = self.get_queryset
        return context


class MessageCard(DetailView):
    """Show all information about message"""
    model = Messages
    template_name = "mailing/message_card.html"
    slug_url_kwarg = "message_slug"

    def get_object(self, queryset=None):
        one_message = super().get_object()
        return one_message

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Message Full Information"
        context["Message"] = self.get_object()
        return context


class MessageCreate(CreateView):
    """Create message"""
    model = Messages
    template_name = "mailing/message_create.html"
    form_class = MessageCreateForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Create Message Template"
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('mailing:messages')

    def form_valid(self, form):
        # save owner of message
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageUpdate(UpdateView):
    """Update message"""
    model = Messages
    fields = ["theme", "body"]
    template_name = "mailing/message_update.html"
    slug_url_kwarg = "message_slug"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Update Message"
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('mailing:messages')

    def form_valid(self, form):
        return super().form_valid(form)


class MessageDelete(DeleteView):
    """Delete message"""
    model = Messages
    template_name = "mailing/delete.html"
    slug_url_kwarg = "message_slug"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Delete Message"
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('mailing:messages')


class TransmissionCard(DetailView):
    """Show all information about transmission"""
    model = Transmission
    template_name = "mailing/transmission_card.html"
    slug_url_kwarg = "transmission_slug"

    def get_object(self, queryset=None):
        one_transmission = super().get_object()
        return one_transmission

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Transmission Full Information"
        current_object = self.get_object()
        context["Transmission"] = current_object
        context["Statistic"] = current_object.get_statistic()
        return context


class TransmissionView(ListView):
    """Show all transmissions for owner / moderator / admin"""
    model = Transmission
    template_name = "mailing/transmissions.html"

    def get_queryset(self):
        queryset = super().get_queryset().all()
        if not self.request.user.is_staff:
            queryset = super().get_queryset().filter(owner=self.request.user)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Transmissions"
        context["Transmissions"] = self.get_queryset()
        return context


class TransmissionCreate(CreateView):
    """Create transmission"""
    model = Transmission
    form_class = TransmissionCreateForm
    template_name = "mailing/transmission_create.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Title"] = "Create New Transmission"
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('mailing:transmissions')

    def form_valid(self, form):

        # Create default statistic for transmission
        current_transmission = self.object
        self.object = form.save()

        # save owner of transmission
        self.object.owner = self.request.user
        self.object.save()

        # Set default data for created transmission
        Statistic.objects.create(transmission_id=self.object.pk)

        # Executing send message
        schedule_transmission_time = self.object.time
        current_time = datetime.now().time()
        if schedule_transmission_time <= current_time:
            message_data = self.object.message.get_info()
            sendmail(self.object.pk, self.object.clients.all(), message_data[0], message_data[1])
            self.object.status = "FINISHED"
            self.object.save()

        return super().form_valid(form)


class TransmissionDelete(DeleteView):
    """Delete transmission"""
    model = Transmission
    template_name = "mailing/delete.html"
    slug_url_kwarg = "transmission_slug"

mailing/templates/mailing/client_card.html
{% extends 'mailing/base.html' %}
{% block body %}

<li>FullName: {{ Client.full_name }}</li>
<li>Comment: {{ Client.comment }}</li>
<li>Email: {{ Client.email }}</li>
<li>Owner: {{ Client.owner|default:"No owner." }}</li>

{% endblock %}

mailing/templates/mailing/client_create.html
{% extends 'mailing/base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="{% if new_client %} Add Client {% else %} Add Client {% endif %}">
</form>
{% endblock %}

mailing/templates/mailing/client_update.html
{% extends 'mailing/base.html' %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p> Title: {{ form.full_name }} </p>
    <p> Email: {{ form.email }} </p>
    <p> Comment: </p>
    <p> {{ form.comment }} </p>


<input type="submit" value="Submit">
</form>
{% endblock %}

mailing/templates/mailing/clients.html
{% extends 'mailing/base.html' %}
{% block body %}
<div class="table-responsive small">
<table class="table table-striped table-sm">
    <thead>
        <tr>
              <th scope="col">#</th>
              <th scope="col">Client Name</th>
              <th scope="col">Mail Address</th>
              <th scope="col">Comment</th>
            {% if perms.mailing.view_clients %}
                <th scope="col">View</th>
            {% endif %}
            {% if perms.mailing.change_clients %}
                <th scope="col">Update</th>
            {% endif %}
            {% if perms.mailing.delete_clients %}
                <th scope="col">Delete</th>
            {% endif %}
            </tr>
        </thead>
{% for client in Clients %}
  <tbody>
    <tr>
        <td>{{client.pk}}</td>
        <td>{{client.full_name}}</td>
        <td>{{client.email}}</td>
        <td>{{client.comment}}</td>

        {% if perms.mailing.view_clients %}
        <td><a href="{% url 'mailing:client_card' client.slug %}"  class="btn btn-sm btn-outline-secondary">View</a></td>
        {% endif %}
        {% if perms.mailing.change_clients %}
        <td><a href="{% url 'mailing:client_update' client.slug %}"  class="btn btn-sm btn-outline-secondary">Update</a></td>
        {% endif %}
        {% if perms.mailing.delete_clients %}
        <td><a href="{% url 'mailing:client_delete' client.slug %}"  class="btn btn-sm btn-outline-secondary">Delete</a></td>
        {% endif %}
    </tr>
  </tbody>
{% endfor %}
</table>
</div>
{% endblock %}

mailing/templates/mailing/delete.html
{% extends 'mailing/base.html' %}
{% block body %}
<div class="center">
	<form method="post">
		{% csrf_token %}
		<p>Are you sure that you want to delete "{{ object }}"?</p>
		<p class="form-buttons">
        <input type="submit" class="btn btn-sm btn-outline-secondary" value="Delete">
		</p>
	</form>
</div>
{% endblock %}

mailing/templates/mailing/message_create.html
{% extends 'mailing/base.html' %}
{% block body %}
{{ test }}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="{% if new_client %} Create Message Template {% else %} Create Message Template {% endif %}">
</form>
{% endblock %}

mailing/templates/mailing/message_update.html
{% extends 'mailing/base.html' %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p> Theme: {{ form.theme }} </p>
    <p> Body: </p> {{ form.body }}

    <p><input type="submit" value="Submit"></p>
</form>
{% endblock %}

mailing/templates/mailing/messages.html
{% extends 'mailing/base.html' %}
{% block body %}
<div class="table-responsive small">
<table class="table table-striped table-sm">
        <thead>
        <tr>
              <th scope="col">#</th>
              <th scope="col">Theme</th>
            {% if perms.mailing.view_messages %}
                <th scope="col">View</th>
            {% endif %}
            {% if perms.mailing.change_messages %}
                <th scope="col">Update</th>
            {% endif %}
            {% if perms.mailing.delete_messages %}
                <th scope="col">Delete</th>
            {% endif %}
        </tr>
        </thead>
{% for message in Messages %}
  <tbody>
    <tr>
        <td>{{message.pk}}</td>
        <td>{{message.theme}}</td>
        {% if perms.mailing.view_messages %}
        <td><a href="{% url 'mailing:message_card' message.slug %}"  class="btn btn-sm btn-outline-secondary">View</a></td>
        {% endif %}
        {% if perms.mailing.change_messages %}
        <td><a href="{% url 'mailing:message_update' message.slug %}"  class="btn btn-sm btn-outline-secondary">Update</a></td>
        {% endif %}
        {% if perms.mailing.delete_messages %}
        <td><a href="{% url 'mailing:message_delete' message.slug %}"  class="btn btn-sm btn-outline-secondary">Delete</a></td>
        {% endif %}

    </tr>
  </tbody>
{% endfor %}
</table>
</div>
{% endblock %}

mailing/templates/mailing/run_scheduler.html
{% extends 'mailing/base.html' %}
{% block body %}
{% endblock %}

mailing/templates/mailing/transmission_card.html
{% extends 'mailing/base.html' %}

{% block body %}

<li>Title: {{ Transmission.title }}</li>
<li>Owner: {{ Transmission.owner|default:"No owner." }}</li>
<li>Time: {{ Transmission.time }}</li>
<li>Frequency: {{ Transmission.frequency }}</li>
<li>Message theme: {{ Transmission.message.theme }}</li>
<li>Message body: {{ Transmission.message.body }}</li>
<li>Is Published: {{ Transmission.is_published }}</li>
<br>
<h5> Clients: </h5>
{% for client in Transmission.clients.all %}
<li>{{ client }}</li>
{%  endfor %}
<br>
<h5>Last Statistics:</h5>
{% for i in Statistic %}
<p>{{ i }} </p>
{% endfor%}
{% endblock %}

mailing/templates/mailing/transmission_create.html
{% extends 'mailing/base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
    {{ form.as_p }}
    </div>
    <input type="submit" value="Create New Transmission">
</form>
{% endblock %}

mailing/templates/mailing/transmission_update.html
{% extends 'mailing/base.html' %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if perms.mailing.change_transmission %}

     <p class="form-control" > Title: {{ form.title }}  </p>
     <p class="form-control"> Time: {{ form.time }} </p>
     <p class="form-control"> Frequency: {{ form.frequency }} </p>
     <p class="form-control"> Message: {{ form.message }} </p>
     <p class="form-control"> Clients: {{ form.clients }} </p>


    {% else %}
         {{ form.title.as_hidden }}
         {{ form.time.as_hidden }}
         {{ form.frequency.as_hidden }}
         {{ form.message.as_hidden }}
         {{ form.clients.as_hidden }}
    {% endif %}

     Active: {{ form.is_published }}
<br><br>
<input type="submit" value="Submit">
</form>
{% endblock %}

mailing/templates/mailing/transmissions.html
{% extends 'mailing/base.html' %}
{% block body %}
<div class="table-responsive small">
<table class="table table-striped table-sm">
        <thead>
        <tr>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Frequency</th>
              <th scope="col">Status</th>
              <th scope="col">Time to Send</th>
              <th scope="col">Is Active</th>
              {% if perms.mailing.view_transmission %}
              <th scope="col">Full View</th>
              {% endif %}
              {% if perms.mailing.view_transmission %}
              <th scope="col">Update</th>
              {% endif %}
              {% if perms.mailing.delete_transmission %}
              <th scope="col">Delete</th>
              {% endif %}


         </tr>
        </thead>

{% for transmission in Transmissions %}
    <tbody>
        <tr>
            <td>{{transmission.pk}}</td>
            <td>{{transmission.title}}</td>
            <td>{{transmission.frequency}}</td>
            <td>{{transmission.status}}</td>
            <td>{{transmission.time | date:"H:i:s"}}</td>

            {% if transmission.is_published %}
                <td> Yes </td>
            {% else %}
                 <td> No </td>
            {% endif %}
            {% if perms.mailing.view_transmission %}
                <td> <a href="{% url 'mailing:transmission_card' transmission.slug %}"  class="btn btn-sm btn-outline-secondary">View</a></td>
            {% endif %}
            {% if perms.mailing.view_transmission %}
                <td> <a href="{% url 'mailing:transmission_update' transmission.slug %}"  class="btn btn-sm btn-outline-secondary">Update</a></td>
            {% endif %}
            {% if perms.mailing.delete_transmission %}
                <td> <a href="{% url 'mailing:transmission_delete' transmission.slug %}"  class="btn btn-sm btn-outline-secondary">Delete</a></td>
            {% endif %}
        </tr>
      </tbody>
 {% endfor %}
</table>
</div>
{% endblock %}